/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { User2WhereInput } from "./User2WhereInput";
import { Type } from "class-transformer";

@ArgsType()
class User2CountArgs {
  @ApiProperty({
    required: false,
    type: () => User2WhereInput,
  })
  @Field(() => User2WhereInput, { nullable: true })
  @Type(() => User2WhereInput)
  where?: User2WhereInput;
}

export { User2CountArgs as User2CountArgs };
